# Generated by Django 3.1 on 2021-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplantı', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplantı',
            name='description',
            field=models.TextField(verbose_name='Katılımcılar'),
        ),
        migrations.AlterField(
            model_name='toplantı',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Toplantı Konu'),
        ),
    ]
