# Generated by Django 3.1 on 2021-04-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplantı', '0002_auto_20210417_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplantı',
            name='tarih',
            field=models.DateTimeField(auto_now=True, verbose_name='Tarih'),
        ),
    ]
