# Generated by Django 3.1 on 2021-04-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplantı', '0003_toplantı_tarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplantı',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
    ]
