# Generated by Django 3.1 on 2021-04-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplantı', '0004_toplantı_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplantı',
            name='bsal',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Bsal'),
        ),
        migrations.AddField(
            model_name='toplantı',
            name='ssal',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Ssal'),
        ),
    ]
